export enum ErrorCode {
	NOT_FOUND = 'NOT_FOUND',
	LAST_PART_IN_SEGMENT = 'LAST_PART_IN_SEGMENT',
	END_OF_RUNDOWN = 'END_OF_RUNDOWN',
	DATABASE_NOT_CONNECTED = 'DATABASE_NOT_CONNECTED',
	MISCONFIGURATION = 'MISCONFIGURATION',
	NOT_ACTIVATED = 'NOT_ACTIVATED',
	ALREADY_ACTIVATED = 'ALREADY_ACTIVATED'
}
