export enum RundownEventType {
	ACTIVATE = 'ACTIVATE',
	DEACTIVATE = 'DEACTIVATE',
	RESET = 'RESET',
	TAKE = 'TAKE',
	SET_NEXT = 'SET_NEXT',
	AD_LIB_PIECE_INSERTED = 'AD_LIB_PIECE_INSERTED',
	INFINITE_RUNDOWN_PIECE_ADDED = 'INFINITE_RUNDOWN_PIECE_ADDED',
	DELETED = 'DELETED',
}
